[versions]
agp = "8.6.1"
kotlin = "1.9.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2025.04.01"
core_ktx = "1.16.0"
activity_ktx = "1.10.1"
camerax_core = "1.4.2"
camerax_view = "1.4.2"
camerax_camera2 = "1.4.2"
camerax_lifecycle = "1.4.2"
mlkit_text = "16.0.1"
retrofit = "2.9.0"
coil = "2.5.0"
coroutines = "1.7.3"


[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core_ktx" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity_ktx" }
camerax-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax_core" }
camerax-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax_camera2" }
camerax-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax_view" }
camerax-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax_lifecycle" }
mlkit-text = { group = "com.google.mlkit", name = "text-recognition", version.ref = "mlkit_text" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
